### ISSUE TITLE
Wrong Commit Date on GitHub Pages

### ISSUE THREAD

**Issue by TrebledJ** [saneef/eleventy-plugin-git-commit-date#2]
This is solved, just posting this for posterity and in case others have the same issue.

When testing locally, the plugin works fine. But when deploying to GitHub pages, you may find that the commit date fetched is wrong (all happen to be the time of the build).

The issue lies with repository checkout. By default, `actions/checkout` won't checkout the entire repository, meaning `git log` can't find the right commit. You can fix this by increasing the fetch depth of `actions/checkout`.
```
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 10000
```

For large repositories, I suppose it will slow down the build. Not sure if there's a better way to alleviate this.

Perhaps it would also be beneficial to highlight this issue in the README, in case new users also encounter it.
